Add bookings
andreyTurkey/java-shareit pull request #2
Opened 2023-06-30 19:35 UTC by andreyTurkey

2023-07-01 14:57 UTC, NikolaiDem requested changes

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    BookingServiceDB bookingServiceDB;
private

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        log.error(bookingAddDto + " - получен запрос на добавление вещи");
Почему error?
Аналогично для остальных методов

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +            "order by id DESC", nativeQuery = true)
Вместо нативных запросов можно использовать jpql. Тогда запросы будут в виде:
select from Booking b where b.user.id = ?1 ....
Аналогично для остальных методов

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                || bookingDto.getStart().isBefore(LocalDateTime.now()) || bookingDto.getEnd().isBefore(LocalDateTime.now()))
Условие bookingDto.getEnd().isBefore(LocalDateTime.now()) бесполезно, потому что 
если bookingDto.getStart().isAfter(bookingDto.getEnd()) false и bookingDto.getStart().isBefore(LocalDateTime.now()) false, то это условие тоже false, иначе очередь до него не дойдет

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        log.error("Бронирование с ID = {} изменено на статус {}", bookingId, text);
Лучше Boolean approve вместо String text

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (text.equals("true")) {
Всегда лучше проверять SOME_CONSTANT.equals(...), чтобы избавиться от возможного NPE

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            if (booking.getStatus().equals(BookingState.APPROVED))
А если booking.getStatus() равен REJECTED?

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        Booking booking = bookingRepository.getById(bookingId);
Deprecated методы лучше не использовать, аналогично для остальных кейсов

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (bookingRepository.findBookingByUserIdEqualsOrderByIdDesc(userId).size() == 0)
Почему отсутствие бронирований у пользователя является ошибкой?

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            case "ALL":
Вместо String лучше создать enum со значениями статусов

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                        .map(bookingMapper::getBookingDto).collect(Collectors.toList());
stream().map(...) дублируется 6 раз, лучше вынести полученную коллекцию в отдельную переменную и после switch case сделать stream().map(...)

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                return bookingRepository.findBookingByOwnerIdOrderByIdDesc(ownerId).stream()
stream().map(...) дублируется 6 раз, лучше вынести полученную коллекцию в отдельную переменную и после switch case сделать stream().map(...)

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            case "ALL":
Вместо String лучше создать enum со значениями статусов

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (!userRepository.existsById(bookingDto.getBooker().getId())) throw new EntityNotFoundException(
Кодстайл : все условия лучше заключать в скобки {}
if (...) {

}
Аналогично для остальных кейсов

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                throw new AvailableException("Unknown state: UNSUPPORTED_STATUS");
Можно NotAvailableException

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/CheckRentHistory.java
> +    BookingRepository bookingRepository;
private

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/CheckRentHistory.java
> +    public CheckRentHistory(BookingRepository bookingRepository) {
Можно использовать lombok для boilerplate code
Аналогично для остальных классов

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/CheckRentHistory.java
> +    public void userTookItem(CommentAddDto commentAddDto) {
По названию метода непонятно, что он делает. Выглядит как юзер бронирует item

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/dto/BookingAddMapper.java
> +    UserServiceDB userServiceDB;
userServiceDB и itemServiceDB избыточны, проще передать user и item в метод маппера

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/dto/BookingMapperGetOwnerDto.java
> +@Component
Мапперы можно не делать бинами, потому что методы в них обычно static.
Аналогично для других мапперов

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/exception/EntityNotFoundExceptionCustom.java
> +
Лишняя строка

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +        return new ErrorResponse(e.getMessage());
Лучше и логировать все исключения.
Аналогично для остальных методов

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    public ErrorResponse handleItemNotFoundException(final EntityNotFoundExceptionCustom e) {
Исключения с одинаковой обработкой лучше внести в один метод.
    @ExceptionHandler({EntityNotFoundException.class, EntityNotFoundExceptionCustom.class})

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/exception/ErrorResponse.java
> +public class ErrorResponse {
Можно добавить @AllArgsConstructor вместо кастомного конструктора

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    final ItemServiceDB itemService;
private

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        log.debug(itemDto + " - вещь была добавлена");
Здесь же вещь еще не была добавлена

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +            @RequestHeader(value = "X-Sharer-User-Id") Long userId) {
X-Sharer-User-Id лучше вынести в константу

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        log.debug(commentAddDto + " - отзыв был добавлен");
Отзыв еще не был добавлен

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    List<Item> findByNameOrDescriptionContainingIgnoreCaseAndAvailableTrue(String text, String text1);
По названию переменных text и text1 непонятно, для чего нужны)

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        if (!Objects.equals(ownerId, userId))
Кодстайл : нужны {}

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        if (text.isBlank()) return new ArrayList<>();
Кодстайл : нужны {} и новая строка

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemServiceDB.java
> +public interface ItemServiceDB {
Почему ItemServiceDB, как связаны сервис и db?

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +public class ItemServiceImpl implements ItemServiceDB {
Кодстайл : к условиям добавить {}

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +public class ItemService {
Класс не используется

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemStorageImpl.java
> +public class ItemStorageImpl implements ItemStorage {
Не используется

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/dto/CommentAddMapper.java
> +    UserServiceDB userServiceDB;
Сервис избыточен, проще передать юзера в метод маппера

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +    @NotNull
Здесь аннотации валидации лишние, этот dto является только исходящим

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/dto/GettingItem.java
> +public class GettingItem {
Класс избыточен, можно использовать ItemRepository

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapperGetOwnerDto.java
> +            List<Booking> orderByIdBookings = bookingRepository.findBookingByOwnerIdAndItemIdAndOrderById(
Проблема N+1 запроса. Необходимо избавиться от обращения к БД при итерировании по каждому item-у (при получении последнего и следующего бронирований). Допустимо делать несколько запросов, но для всего списка item-ов сразу. Например, одним запросом получить все последние бронирования для списка item-ов. Еще одним одним запросом получить все следующие бронирования и тд. Но не обращаться по каждому item-у в БД
Аналогично для комментариев

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    List<Long> comments = new ArrayList<>();
Поле лишнее, создает проблему N+1 запроса

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/UserStorage.java
> +public interface UserStorage {
Не используется

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    public boolean equals(Object o) {
Для чего переопределяются equals и hashCode?
Аналогично для остальных моделей

2023-07-01 14:57 UTC, NikolaiDem commented on src/main/resources/schema.sql
> +drop table IF EXISTS users CASCADE;
Удалять таблицы не нужно

2023-07-01 17:21 UTC, andreyTurkey commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (bookingRepository.findBookingByUserIdEqualsOrderByIdDesc(userId).size() == 0)
Ведь отсутствие бронирований у пользователя при запросе приведет к исключению. В тестах проверка номера 100, но мог быть юзер 1 или 2 без бронирований.

2023-07-04 14:24 UTC, andreyTurkey commented on src/main/java/ru/practicum/shareit/item/dto/GettingItem.java
> +public class GettingItem {
Класс стал неиспользуемым, но при полном удалении спринг ругается на его отсутствие((

2023-07-04 15:37 UTC, andreyTurkey commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +            "order by id DESC", nativeQuery = true)
Попозже обязательно разберусь с jpql)

2023-07-05 14:55 UTC, NikolaiDem requested changes

2023-07-05 14:55 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public BookingDto updateStatus(@Valid
Здесь @Valid для Long не нужен

2023-07-05 14:55 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                             defaultValue = "ALL") String state) {
Если определено дефолтное значение, то required = false лишнее.
Аналогично для остальных методов

2023-07-05 14:55 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        log.debug("Получен запрос на изменение статуса бронирования с ID = {} на статус {}", bookingId, APPROVED);
Boolean approved

2023-07-05 14:55 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    private final Boolean APPROVE_STATUS = true;
Лучше перенести непосредственно в метод updateStatus(...)

2023-07-05 14:55 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        }
Еще лучше проверить, что вещь не забронирована никем другим на запрашиваемые даты.

2023-07-05 14:55 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            booking.setStatus(BookingState.REJECTED);
А если бронирование уже имеет статус APPROVED, можно ли его изменить на Rejected?

2023-07-05 14:55 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (bookingRepository.findBookingByUserIdEqualsOrderByIdDesc(userId).size() == 0) {
Почему при отсутствии бронирований ошибка?

2023-07-05 14:55 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (bookingRepository.findBookingByOwnerIdOrderByIdDesc(ownerId).size() == 0) {
Почему при отсутствии бронирований ошибка?

2023-07-05 14:55 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            throw new EntityNotFoundException("Вещь не найдена.");
При формировании исключений лучше добавлять детали ошибки, например, вещь с каким id не найдена.
Исправить во всех кейсах

2023-07-05 14:55 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/CheckRentHistory.java
> +    public void isUserTookItem(CommentAddDto commentAddDto) {
Методы, начинающиеся с is.... обычно возвращают boolean

2023-07-05 14:55 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/ConverterStatus.java
> +    public static BookingState getBookingState(String status) {
Этот метод лучше перенести в BookingState

2023-07-05 14:55 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    List<Item> findByNameOrDescriptionContainingIgnoreCaseAndAvailableTrue(String name, String description);
Hibernate генерирует такой запрос для поиска:
    select
        item0_.id as id1_2_,
        item0_.available as availabl2_2_,
        item0_.description as descript3_2_,
        item0_.name as name4_2_,
        item0_.owner as owner5_2_ 
    from
        public.items item0_ 
    where
        item0_.name=? 
        or (
            upper(item0_.description) like upper(?) escape ?
        ) 
        and item0_.available=true
        
Так имелось ввиду?

2023-07-05 14:55 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/dto/GettingItem.java
> +public class GettingItem {
Почему ругается?

2023-07-05 14:55 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +        if (userUpdateDto.getName() != null) user.setName(userUpdateDto.getName());
Кодстайл: добавить скобки {}
if () {
}

2023-07-05 14:55 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +public class ItemService {
Все служебные методы сделать private, аналогично для других сервисов

2023-07-05 14:55 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        List<Item> itemsByOwner = itemRepository.findAllByOwner(ownerId);
Осталась пара штрихов. Итак, вы добавили возможность бронировать вещи. Теперь нужно, чтобы владелец видел даты последнего и ближайшего следующего бронирования для каждой вещи, когда просматривает список (GET /items).

В строке 84 найдены все предметы юзера с id = ownerId, ок
В строке 86 найдены все бронирования юзера с id = ownerId
А нужно найти бронирования не пользователя ownerId, а бронирования для каждой вещи.
Аналогично для комментариев

2023-07-05 19:19 UTC, andreyTurkey commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    List<Item> findByNameOrDescriptionContainingIgnoreCaseAndAvailableTrue(String name, String description);
Да. Ищет в названии или описании

2023-07-07 08:58 UTC, NikolaiDem approved these changes

2023-07-07 09:31 UTC, merged