Первый коммит - впереди тесты БД
andreyTurkey/java-shareit pull request #3
Opened 2023-07-13 18:59 UTC by andreyTurkey

2023-07-18 09:39 UTC, NikolaiDem requested changes

2023-07-18 09:39 UTC, NikolaiDem commented on src/main/resources/schema.sql
> +drop table IF EXISTS users CASCADE;
Удалять таблицы не нужно, это прод схема

2023-07-18 09:39 UTC, NikolaiDem commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS answers (
Для чего эта таблица?

2023-07-18 09:39 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +@EqualsAndHashCode
Для чего переопределение equals и hashCode?
Аналогично для остальных сущностей

2023-07-18 09:39 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +    public boolean isUserExists(Long userId) throws EntityNotFoundException {
throws EntityNotFoundException не нужен, потому что это непроверяемое исключение

2023-07-18 09:39 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/ItemRequestsService.java
> +public class ItemRequestsService {
Все служебные методы сделать private

2023-07-18 09:39 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/ItemRequestsService.java
> +        for (ItemRequestPublicDto requestPublicDto : requests) {
От вложенного цикла лучше избавиться, заменив items или requests на мапу

2023-07-18 09:39 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/ItemRequestsService.java
> +        List<ItemRequestJoinAnswer> requests = em.createQuery(
Детали запроса лучше перенести в репозиторий, аналогично для остальных методов

2023-07-18 09:39 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/ItemRequestsService.java
> +                break;
Точно ли здесь имелся ввиду break? Нужен выход из цикла?

2023-07-18 09:39 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/ItemRequestsService.java
> +        for (ItemRequestPublicDto requestPublicDto : requests) {
Был специально создан ItemRequestPublicDto, который содержит в себе item и request, но далее он все равно разбивается на 2 списка items и requests. Тогда был ли смысл в ItemRequestPublicDto ?)

2023-07-18 09:39 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/ItemRequestsService.java
> +        Optional<ItemRequestJoinAnswer> requestJoinAnswers = getRequestByIdJoinAnswer(requestId)
Не совсем подходящий метод getRequestByIdJoinAnswer для получения первого ItemRequestJoinAnswer. Метод возвращает список items, сджойненных с их запросами, но из этого ответа извлекается только первый, и берется из него сам запрос. Тогда можно было бы создать метод, который вернет только сам ItemRequest, а по его id определены уже items

2023-07-18 09:39 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/ItemRequestsService.java
> +        if (from < 0 || size <= 0) {
Лучше сделать валидацию параметров в контроллере

2023-07-18 09:39 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/ItemRequestsService.java
> +            itemRequestsByPageable = itemRequestsRepository.findAll().stream().filter(t -> {
Кодстайл:
            itemRequestsByPageable = itemRequestsRepository.findAll().stream()
                .filter(t -> (!t.getUserId().equals(userId)))
                .map(ItemRequestMapper::getItemRequestPublicDto)
                .collect(Collectors.toList());

Исправить в остальных методах

2023-07-18 09:39 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/ItemRequestsService.java
> +        Sort sortById = Sort.by(Sort.Direction.DESC, "id");
Запросы сортируются по дате создания: от более новых к более старым.
Аналогично для остальных методов

2023-07-18 09:39 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/ItemRequestsService.java
> +            for (Item item : findAllByList) {
Избавиться от вложенного цикла

2023-07-18 09:39 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    @Query("select i from Item i where i.requestId in :ids")
Query лишний, можно описать только с помощью метода

2023-07-18 09:39 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            Sort sortById = Sort.by(Sort.Direction.DESC, "id");
Запросы сортируются по дате создания: от более новых к более старым

2023-07-18 09:39 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        List<Long> bookingsIds = bookingRepository.findBookingByUserId(userId, page).getContent().stream().map(t -> {
Кодстайл:
        List<Long> bookingsIds = bookingRepository.findBookingByUserId(userId, page)
            .getContent()
            .stream()
            .map(Booking::getId)
            .collect(Collectors.toList());

Аналогично для остальных методов

2023-07-18 09:39 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
>          List<Booking> bookings = em.createQuery(
Детали реализации запроса лучше перенести в репозиторий, аналогично для остальных методов

2023-07-18 09:39 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
>  public class BookingServiceImpl implements BookingService {
Все служебные методы сделать private

2023-07-18 09:39 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    @Query("SELECT b FROM Booking b WHERE b.user.id = :id")
А нужен ли здесь query? Можно описать только с помощью сигнатур методов.
Аналогично для остальных методов

2023-07-18 09:39 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                    @RequestParam(value = "from", required = false) Integer from,
Лучше валидацию на не отрицательность параметров задать здесь через аннотации PositiveOrZero или Positive.
Аналогично для остальных методов

2023-07-18 19:40 UTC, andreyTurkey commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            Sort sortById = Sort.by(Sort.Direction.DESC, "id");
У бронирования нет ни даты создания ни времени. И чем плох айди?

2023-07-18 19:45 UTC, andreyTurkey commented on src/main/resources/schema.sql
> +drop table IF EXISTS users CASCADE;
Без удаления таблиц на гитхабе валятся все тесты (юнит и интеграционные)

2023-07-18 19:46 UTC, andreyTurkey commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +@EqualsAndHashCode
без переопределения валятся тесты - рекомендация в лекциях всегда переопределять и наставника для решения проблемы тестирования

2023-07-18 19:47 UTC, andreyTurkey commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    @Query("select i from Item i where i.requestId in :ids")
вариант List<Item> findAllByRequestId(Iterable ids) прводит к исключению - "org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'bookingController' defined in file [/Users/andreyturkey/Documents/dev/java-shareit/target/classes/ru/practicum/shareit/booking/BookingController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'bookingServiceImpl' defined in file [/Users/andreyturkey/Documents/dev/java-shareit/target/classes/ru/practicum/shareit/booking/BookingServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'itemService' defined in file [/Users/andreyturkey/Documents/dev/java-shareit/target/classes/ru/practicum/shareit/item/ItemService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'itemRepository' defined in ru.practicum.shareit.item.ItemRepository defined in [@EnableJpaRepositories](https://app.pachca.com/chats/5552746#) declared on JpaRepositoriesRegistrar.EnableJpaRepositoriesConfiguration: Invocation of init method failed; nested exception is org.springframework.data.repository.query.QueryCreationException: Could not create query for public abstract java.util.List ru.practicum.shareit.item.ItemRepository.findAllByRequestId(java.lang.Iterable); Reason: Failed to create query for method public abstract java.util.List ru.practicum.shareit.item.ItemRepository.findAllByRequestId(java.lang.Iterable)! Operator SIMPLE_PROPERTY on requestId requires a scalar argument, found interface java.lang.Iterable in method public abstract java.util.List ru.practicum.shareit.item.ItemRepository.findAllByRequestId(java.lang.Iterable).; nested exception is java.lang.IllegalArgumentException: Failed to create query for method public abstract java.util.List ru.practicum.shareit.item.ItemRepository.findAllByRequestId(java.lang.Iterable)! Operator SIMPLE_PROPERTY on requestId requires a scalar argument, found interface java.lang.Iterable in method public abstract java.util.List ru.practicum.shareit.item.ItemRepository.findAllByRequestId(java.lang.Iterable)."

2023-07-19 22:36 UTC, NikolaiDem requested changes

2023-07-19 22:36 UTC, NikolaiDem commented on src/main/resources/schema.sql
> +drop table IF EXISTS users CASCADE;
Какие тесты валятся?

2023-07-19 22:36 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +@EqualsAndHashCode
В бд уникальность объектов реализована только по id. А в модели уникальность объектов реализуется по всем параметрам в случае такого переопределения equals и hashCode. Получается несоответствие поведения.
https://vladmihalcea.com/how-to-implement-equals-and-hashcode-using-the-jpa-entity-identifier/
Какие тесты валятся?

2023-07-19 22:36 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +    public boolean isUserExists(Long userId)  {
Метод false никогда не возвращает, поэтому проверки в вызывающих его методах, например,
if (!userService.isUserExists(userId)) {
            throw new EntityNotFoundException("Проверьте ID = " + userId + " пользователя");
        }
Никогда не бывают истинными, и такой код избыточен .
Аналогично для остальных сервисов

2023-07-19 22:36 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestJoinAnswer.java
> +public class ItemRequestJoinAnswer {
Не используется

2023-07-19 22:36 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/ItemRequestsService.java
> +    public List<ItemRequestPublicDto> getAllRequestByUserId(Long userId) {
Можно короче:
    public List<ItemRequestPublicDto> getAllRequestByUserId(Long userId) {
        userService.isUserExists(userId);

        List<ItemRequest> allRequestsByUser = itemRequestsRepository.getItemRequestByUserId(userId);

        List<Long> requestIds = allRequestsByUser
            .stream()
            .map(ItemRequest::getId)
            .collect(Collectors.toList());

        Map<Long, List<ItemPublicDto>> itemDtosByRequestId = itemRepository.findAllByRequestIdIn(requestIds).stream()
            .map(ItemMapper::getItemPublicDtoFromItem)
            .collect(Collectors.groupingBy(ItemPublicDto::getRequestId, Collectors.toList()));
        
        return allRequestsByUser.stream()
            .map(ItemRequestMapper::getItemRequestPublicDto)
            .map(itemRequestPublicDto -> {
                itemRequestPublicDto.setItems(itemDtosByRequestId.getOrDefault(itemRequestPublicDto.getId(), Collections.emptyList()));
                return itemRequestPublicDto;
            })
            .collect(Collectors.toList());
    }

Аналогично для getAllRequestByPageable

2023-07-19 22:36 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            Sort sortById = Sort.by(Sort.Direction.DESC, "id");
id не всегда бывает упорядоченным в смысле бизнес поведения (даты создания и т.д.)

2023-07-20 17:29 UTC, NikolaiDem approved these changes

2023-07-21 05:32 UTC, merged